// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4_7zGQUtzNmXOiqbA9ldsSL6fakQ87xA',
    appId: '1:1011035911487:web:bb8942feb93218ad4b8f8a',
    messagingSenderId: '1011035911487',
    projectId: 'flutter-fcm-123456',
    authDomain: 'flutter-fcm-123456.firebaseapp.com',
    storageBucket: 'flutter-fcm-123456.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgIl9r9W7Y7EgpE4e-Ns3Ly1Kgieq53q4',
    appId: '1:1011035911487:android:332113e3ecd9f6e64b8f8a',
    messagingSenderId: '1011035911487',
    projectId: 'flutter-fcm-123456',
    storageBucket: 'flutter-fcm-123456.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7NzGU5pEaJwwsNfaciDMIpVCTZRVY92k',
    appId: '1:1011035911487:ios:8736d63f0166e4904b8f8a',
    messagingSenderId: '1011035911487',
    projectId: 'flutter-fcm-123456',
    storageBucket: 'flutter-fcm-123456.appspot.com',
    iosClientId: '1011035911487-n4ht4ik7kq30a1gp1fj6lnl284be8g2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7NzGU5pEaJwwsNfaciDMIpVCTZRVY92k',
    appId: '1:1011035911487:ios:0e91f353d9f027114b8f8a',
    messagingSenderId: '1011035911487',
    projectId: 'flutter-fcm-123456',
    storageBucket: 'flutter-fcm-123456.appspot.com',
    iosClientId: '1011035911487-n21lqf5i9u4g7d8h245jrpllfeq3voia.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFcm.RunnerTests',
  );
}
